%%{init: {'sequence': {'messageFontSize': 15, 'actorFontSize': 15, 'noteFontSize': 14, 'messageMargin': 26, 'boxMargin': 6, 'boxTextMargin': 4, 'noteMargin': 6, 'actorMargin': 70, 'mirrorActors': false, 'wrap': false}}}%%
sequenceDiagram
    participant App as Application
    participant FL as FXMLLoader
    participant C as Controller
    App->>FL: load(compteur.fxml)
    FL->>C: new Controller()
    Note over C: @FXML = null
    FL->>C: assigne les nœuds
    Note over C: @FXML prêts
    FL->>C: initialize()
    Note over C: bindings, peuplement
    FL-->>App: racine du graphe
